routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();  

// Alle prefixen van het CMS
Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function() {

        // Dashboard controller
        Route::get('/', 'DashboardController@index')->name('index');


        // Menu - pagina
        Route::get('/menu', 'MenuController@index')->name('menu.index');
        Route::post('/menu/store', 'MenuController@store')->name('menu.store');
        Route::post('/menu/put/{$menu}', 'MenuController@put')->name('menu.put');
        Route::post('/menu/delete/{$menu}', 'MenuController@delete')->name('menu.delete');
        

        // Pagina - pagina
        Route::get('/page', 'PageController@index')->name('page.index');
        Route::get('/page/create', 'PageController@create')->name('page.create');
        Route::post('/page/create/store', 'PageController@store')->name('page.store');
        Route::get('/page/update/{page}', 'PageController@update')->name('page.update');
        Route::post('/page/update/put/{page}', 'PageController@put')->name('page.put');
        Route::get('/page/builder/{page}', 'PageController@builder')->name('page.builder');
        Route::post('/page/builder/save/{page}', 'PageController@save')->name('page.save');
        Route::post('/page/delete/{page}', 'PageController@delete')->name('page.delete');


        // Thema - pagina
        Route::get('/theme', 'ThemeController@index')->name('theme.index');
        Route::get('/theme/create', 'ThemeController@create')->name('theme.create');
        Route::post('/theme/create/store', 'ThemeController@store')->name('theme.store');
        Route::get('/theme/detail/{theme}', 'ThemeController@detail')->name('theme.detail');
        Route::get('/theme/update/{theme}', 'ThemeController@update')->name('theme.update');
        Route::post('/theme/update/put/{theme}', 'ThemeController@put')->name('theme.put');
        Route::post('/theme/delete/{theme}', 'ThemeController@delete')->name('theme.delete');


        // Variabele module
        Route::get('/ModuleItem/{module}', 'ModuleItemController@index')->name('moduleitem.index');
        Route::get('/ModuleItem/{module}/create', 'ModuleItemController@create')->name('moduleitem.create');
        Route::post('/ModuleItem/{module}/create/store', 'ModuleItemController@store')->name('moduleitem.store');
        Route::get('/ModuleItem/{module}/update/{item}', 'ModuleItemController@update')->name('moduleitem.update');
        Route::post('/ModuleItem/{module}/update/put/{item}', 'ModuleItemController@put')->name('moduleitem.put');
        Route::post('/ModuleItem/{module}/delete/{item}', 'ModuleItemController@delete')->name('moduleitem.delete');


        // Module - pagina
        Route::get('/module', 'ModuleController@index')->name('module.index');
        Route::get('/module/create', 'ModuleController@create')->name('module.create');
        Route::post('/modules/create/store', 'ModuleController@store')->name('module.store');
        Route::get('/modules/update/{module}', 'ModuleController@update')->name('module.update');
        Route::post('/modules/update/put/{module}', 'ModuleController@put')->name('module.put');
        Route::get('/modules/builder/{module}', 'ModuleController@builder')->name('module.builder');
        Route::post('/module/builder/save/{module}', 'ModuleController@save')->name('module.save');
        Route::post('/modules/delete/{module}', 'ModuleController@delete')->name('module.delete');


        // Templates - pagina
        Route::get('/template', 'TemplateController@index')->name('template.index');
        Route::get('/template/create', 'TemplateController@create')->name('template.create');
        Route::post('/template/create/store', 'TemplateController@store')->name('template.store');
        Route::get('/template/update/{template}', 'TemplateController@update')->name('template.update');
        Route::post('/template/update/put/{template}', 'TemplateController@put')->name('template.put');
        Route::get('/template/builder/{template}', 'TemplateController@builder')->name('template.builder');
        Route::post('/template/builder/save/{template}', 'TemplateController@save')->name('template.save');
        Route::post('/template/delete/{template}', 'TemplateController@delete')->name('template.delete');


        // Atribute - pagina
        Route::get('/attribute', 'AttributeController@index')->name('attribute.index');
        Route::get('/attribute/create', 'AttributeController@create')->name('attribute.create');
        Route::post('/attribute/create/store', 'AttributeController@store')->name('attribute.store');
        Route::get('/attribute/update/{attribute}', 'AttributeController@update')->name('attribute.update');
        Route::post('/attribute/update/put/{attribute}', 'AttributeController@put')->name('attribute.put');
        Route::post('/attribute/delete/{attribute}', 'AttributeController@delete')->name('attribute.delete');


        // Formulieren - pagina
        Route::get('/forms', 'FormsController@index')->name('forms.index');
        Route::get('/forms/create', 'FormsController@create')->name('forms.create');
        Route::post('/forms/create/store', 'FormsController@store')->name('forms.store');
        Route::get('/forms/update/{forms}', 'FormsController@update')->name('forms.update');
        Route::post('/forms/update/put/{forms}', 'FormsController@put')->name('forms.put');
        Route::post('/forms/delete/{forms}', 'FormsController@delete')->name('forms.delete');
        Route::get('/forms/builder/{forms}', 'FormsController@builder')->name('forms.builder');
        Route::post('/forms/builder/save/{forms}', 'FormsController@save')->name('forms.save');
        Route::get('/forms/export/{forms}', 'FormsController@export')->name('forms.export');


        // Mailen - pagina
        Route::get('/mails', 'MailController@index')->name('mails.index');
        Route::get('/mails/create', 'MailController@create')->name('mails.create');
        Route::post('/mails/create/store', 'MailController@store')->name('mails.store');
        Route::get('/mails/update/{mail}', 'MailController@update')->name('mails.update');
        Route::post('/mails/update/put/{mail}', 'MailController@put')->name('mails.put');
        Route::post('/mails/delete/{mail}', 'MailController@delete')->name('mails.delete');
        Route::get('/mails/builder/{mail}', 'MailController@builder')->name('mails.builder');
        Route::post('/mails/builder/save/{mail}', 'MailController@save')->name('mails.save');


        // Gebruikers - pagina
        Route::get('/user', 'UserController@index')->name('user.index');
        Route::get('/user/create', 'UserController@create')->name('user.create');
        Route::post('/user/create/store', 'UserController@store')->name('user.store');
        Route::get('/user/update/{id}', 'UserController@update')->name('user.update');
        Route::post('/user/update/put/{user}', 'UserController@put')->name('user.put');
        Route::post('/user/delete/{user}', 'UserController@delete')->name('user.delete');


        // Rechten - pagina
        Route::get('/role', 'RoleController@index')->name('role.index');
        Route::get('/role/create', 'RoleController@create')->name('role.create');
        Route::post('/role/create/store', 'RoleController@store')->name('role.store');
        Route::get('/role/update/{role}', 'RoleController@update')->name('role.update');
        Route::post('/role/update/put/{role}', 'RoleController@put')->name('role.put');
        Route::post('/role/delete/{role}', 'RoleController@delete')->name('role.delete');


        // Setting - pagina
        Route::get('/setting/{page}', 'SettingsController@index')->name('setting.index');
        Route::post('/setting/put/{page}', 'SettingsController@put')->name('setting.put');
});

// Alle prefixen van de voorkant 
Route::prefix('/')
    ->group(function () {
        Route::get('/', 'FrontendController@index');
        Route::get('/{page_name}', 'FrontendController@pages');
        Route::post('/{page_name}', 'FrontendController@pages');
        Route::get('/{page_name}/{detail}', 'FrontendController@detail');


        // Alle ajax requests
        Route::post('/ajax/post/createMailResult', function () {
            if (Request::ajax()) {
                $data = Request::except(['_token']);
                $form = App\FormsModel::where('name', $data['name'])->get()->first();
                DB::table('forms_'.$data['name'])->insert(Request::except(['name', '_token']));
                Mail::to($data['Email'], $data['Voornaam'])->send(new App\Mail\ResponseForm($data, $form->Mails->MailData));

                return response()->json(['msg' => 'Het werkt']);
            } else {
                return response()->json(['msg' => 'Het werkt niet'], 406);
            }   
        });

        Route::post('/ajax/post/updateMessage', function () {
            if (Request::ajax()) {
                $data = Request::except(['_token']);
                $message = App\MessageModel::find($data['id']);
                $message->update($data);
                return response()->json(['msg', 'Het werkt'], 200);
            }

            return response()->json(['msg' => 'Het werkt niet'], 406);
        });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\RoleModel;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'role_id', 'password', 'image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * Relation: Role
     */
    public function Role()
    {
        return $this->belongsTo(RoleModel::class, 'role_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

use App\User;
use App\MessageModel;


class UserController extends Controller
{
    /**
     * @var Carbon $_date
     */
    protected $_date;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->_date = Carbon::now();
    }


    /**
     * Laat de read pagina zien
     * 
     * @return Illuminate\Http\Request view;
     */
    public function index()
    {
        $users = User::get();

        return view('users.read', compact('users'));
    }


    /**
     * Functie voor het aanmaken van de gebruiker
     * 
     * @return Illuminate\Http\Request view;
     */
    public function create()
    {
        $users = User::get();

        return view('users.create', compact('users'));
    }


    /**
     * Functie voor het opslaan van de create
     * 
     * @param Illuminate\Http\Request $request;
     * @return Illuminate\Http\Request redirect;
     */
    public function store(Request $request)
    {
        $request->validate([
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:8',
            'password_sec' => 'required|min:8|same:password'
        ]);

        $user = User::create($this->transformForm($request, null));
        $this->createMessage(['Succes', 'Gebruiker succesvol toegevoegd', 'fas fa-check-circle', 0, $this->_date->toDateString(), $this->_date->toTimeString(),]);
        return redirect('/admin/user')->with('status', 'Gebruiker succesvol toegevoegd!');
    }


    /**
     * Functie voor het updaten van de gebruiker
     * 
     * @param Number $id
     * @return Illuminate\Http\Request view;
     */
    public function update($id)
    {
        $users = User::get();
        $user = User::where('id', $id)->get();

        return view('users.update', compact('users', 'user'));
    }


    /**
     * Functie voor het opslaan van de gegevens
     * 
     * @param Request $request
     * @param User $user
     * @return Illuminate\Http\Request view;
     */
    public function put(Request $request, User $user)
    {
        $request->validate([
            'email' => 'required|email',
            'password' => 'nullable|min:8',
            'password_sec' => 'nullable|min:8|same:password',
        ]);

        $user->update($this->transformForm($request, $user));
        $this->createMessage(['Succes', 'Gebruiker succesvol geüpdated', 'fas fa-check-circle', 0, $this->_date->toDateString(), $this->_date->toTimeString(),]);
        return redirect('/admin/user')->with('status', 'Gebruiker succesvol geüpdated!');
    }


    /**
     * Functie voor het verwijderen van de gebruiker
     * 
     * @param User $user;
     * @return Illuminate\Http\Request view;
     */
    public function delete(User $user)
    {
        $user->delete();
        $this->createMessage(['Succes', 'Gebruiker succesvol verwijderd', 'fas fa-check-circle', 0, $this->_date->toDateString(), $this->_date->toTimeString(),]);
        return redirect('/admin/user')->with('status', 'Gebruiker succesvol verwijderd!');
    }


    /**
     * Functie voor het verwerken van een afbeelding
     *
     * @param Request $request
     * @param User $user
     * @return string
     *
    */
    private function checkImage($request, $user)
    {
        if (gettype($user) == "object") {
            Storage::delete($user->image);
        }

        if (is_null($request->file('image'))) {
            return null;
        }

        return $request->file('image')->store('media');
    }


    /**
     * Functie voor het aanmaken van een melding
     * 
     * @param array $data
     * @return MessageModel 
     */
    private function createMessage(array $data)
    {
        return MessageModel::create([
            'name' => $data[0],
            'message' => $data[1],
            'image' => $data[2],
            'read' => $data[3],
            'date' => $data[4],
            'time' => $data[5],
        ]);
    }


    /**
     * Standaard array voor de form
     * 
     * @param Request $request;
     * @param User $user;
     * @return Array;
     */
    private function transformForm($request, $user)
    {
        return [
            'name' => $request->input('username'),
            'email' => $request->input('email'),
            'role_id' => $request->input('role'),
            'password' => Hash::make($request->input('password')),
            'image' => $this->checkImage($request, $user),
        ];
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')
@section('title', 'Gebruikers - Create')
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Gebruikers
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="{{ route('admin.user.index') }}">Gebruikers</a></li>
        <li><a href="{{ route('admin.user.create') }}">Gebruikers aanmaken</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Gebruikers aanmaken</h3>
        </div>
        
        <form action="{{ route('admin.user.store') }}" method="POST" enctype="multipart/form-data">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-image">
                            <input type="file" id="file_id" name="image" style="display: none;" />
                            <button onclick="return false" id="button_id" class="create-input-image">
                                <i id="imgIcon" class="fas fa-plus-square"></i>
                                <img id="imgPrev" width="100%" height="100%" style="display: none" />
                            </button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <!-- Gebruikersnaam -->
                        <div class="form-group">
                            <label class="form-text">Gebruikersnaam *</label>
                            <input type="text" name="username" class="form-control" placeholder="Gebruikersnaam.." required />
                        </div>
                        <!-- Email adres -->
                        <div class="form-group">
                            <label class="form-text">Email adres *</label>
                            <input type="email" name="email" class="form-control" placeholder="Email adres.." required />    
                        <div>
                        <!-- Rechten -->
                        <div class="form-group">
                            <label class="form-text">Rechten *</label>
                            <select class="form-control" name="role">
                                @foreach($users as $role)
                                    <option value={{ $role->role->id }}>{{ $role->role->title }}</option>
                                @endforeach
                            </select>
                        </div>
                        <!-- Wachtwoord -->
                        <div class="form-group">
                            <label class="form-text">Wachtwoord *</label>
                            <input type="password" name="password" class="form-control" placeholder="Wachtwoord.." required />
                        </div>
                        <!-- Wachtwoord herhalen -->
                        <div class="form-group">
                            <label class="form-text">Wachtwoord herhalen *</label>
                            <input type="password" name="password_sec" class="form-control" placeholder="Wachtwoord herhalen.." required />
                        </div>
                        <!-- Submit knop -->
                        <div class="form-group">
                            @csrf
                            <input type="submit" name="submit" class="btn btn-success" value="Gebruiker aanmaken" />
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>

document.getElementById('button_id').addEventListener('click', getFile);
document.getElementById('button_id').onsubmit = function() {
    return false;
};

function getFile() {
    document.getElementById('file_id').click();
}

 /**
     * Functie om live afbeeldingen op de  
     * Voorkant van de website te kunnen bekijken
     */
     function readImgURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#imgPrev').attr('src', e.target.result);
            }

            document.getElementById('imgIcon').style.display = "none";
            document.getElementById('imgPrev').style.display = "block";

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#file_id").change(function () {
        readImgURL(this);
    });
</script>

@endsection

resources/views/users/read.blade.php
@extends('layouts.master')
@section('title', 'Gebruikers - Read')
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Gebruikers
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.user.index') }}">Gebruikers</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Gebruikers</h3>
            <a class="btn btn-success pull-right" href="{{ route('admin.user.create') }}">Nieuw</a>
        </div>
        
        <table id="myexample" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Gebruikersnaam</th>
                    <th>Email adres</th>
                    <th>Afbeelding</th>
                    <th>Bewerken</th>
                    <th>Verwijderen</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->image }}</td>
                        <td><a class="btn btn-warning" href="{{ route('admin.user.update', $user->id) }}"><i class="fas fa-pencil-alt"></i></a></td>
                        <td><a class="btn btn-danger" href="{{ route('admin.user.delete', $user->id) }}"
                          onclick="event.preventDefault();sure();document.getElementById('delete-form').submit();">
                          <i class="far fa-trash-alt"></i></a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        
    </div>

    <form id="delete-form" method="post" action="{{ route('admin.user.delete', [$user->id ?? '']) }}" style="display:none;">
      @csrf
    </form>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>

  function sure() {
    return confirm("Weet je het zeker dat je de gebruiker wilt verwijderen!");
  }

  $(function () {
        $('#myexample').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
</script>

@endsection

resources/views/users/update.blade.php
@extends('layouts.master')
@section('title', 'Gebruikers - Update')
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Gebruikers
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="{{ route('admin.user.index') }}">Gebruikers</a></li>
        <li><a href="{{ route('admin.user.update', [$user[0]->id]) }}">Gebruikers updaten</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Gebruikers updaten</h3>
        </div>
        
        <form action="{{ route('admin.user.put', $user[0]->id) }}" method="POST" enctype="multipart/form-data">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-image">
                            <input type="file" id="file_id" name="image" style="display: none;" />
                            <button onclick="return false" id="button_id" class="create-input-image">
                                <i id="imgIcon" class="fas fa-plus-square"></i>
                                <img id="imgPrev" src="{{ $user[0]->image }}" width="100%" height="100%" style="display: none" />
                            </button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <!-- Gebruikersnaam -->
                        <div class="form-group">
                            <label class="form-text">Gebruikersnaam *</label>
                            <input type="text" name="username" class="form-control" value="{{ $user[0]->name }}" placeholder="Gebruikersnaam.." required />
                        </div>
                        <!-- Email adres -->
                        <div class="form-group">
                            <label class="form-text">Email adres *</label>
                            <input type="email" name="email" class="form-control" value="{{ $user[0]->email }}" placeholder="Email adres.." required />    
                        <div>
                        <!-- Rechten -->
                        <div class="form-group">
                            <label class="form-text">Rechten *</label>
                            <select class="form-control" name="role">
                                @foreach($users as $role)
                                    <option value={{ $role->role->id }} @if($role->role->id == $user[0]->role_id) selected @endif>{{ $role->role->title }}</option>
                                @endforeach
                            </select>
                        </div>
                        <!-- Wachtwoord -->
                        <div class="form-group">
                            <label class="form-text">Wachtwoord</label>
                            <input type="password" name="password" class="form-control" placeholder="Wachtwoord.." />
                        </div>
                        <!-- Wachtwoord herhalen -->
                        <div class="form-group">
                            <label class="form-text">Wachtwoord herhalen</label>
                            <input type="password" name="password_sec" class="form-control" placeholder="Wachtwoord herhalen.." />
                        </div>
                        <!-- Submit knop -->
                        <div class="form-group">
                            @csrf
                            <input type="submit" name="submit" class="btn btn-success" value="Gebruiker updaten" />
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>

document.getElementById('button_id').addEventListener('click', getFile);
document.getElementById('button_id').onsubmit = function() {
    return false;
};

function getFile() {
    document.getElementById('file_id').click();
}

 /**
     * Functie om live afbeeldingen op de  
     * Voorkant van de website te kunnen bekijken
     */
     function readImgURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#imgPrev').attr('src', e.target.result);
            }

            document.getElementById('imgIcon').style.display = "none";
            document.getElementById('imgPrev').style.display = "block";

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#file_id").change(function () {
        readImgURL(this);
    });
</script>

@endsection