routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();  

// Alle prefixen van het CMS
Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function() {

        // Dashboard controller
        Route::get('/', 'DashboardController@index')->name('index');


        // Menu - pagina
        Route::get('/menu', 'MenuController@index')->name('menu.index');
        Route::post('/menu/store', 'MenuController@store')->name('menu.store');
        Route::post('/menu/put/{$menu}', 'MenuController@put')->name('menu.put');
        Route::post('/menu/delete/{$menu}', 'MenuController@delete')->name('menu.delete');
        

        // Pagina - pagina
        Route::get('/page', 'PageController@index')->name('page.index');
        Route::get('/page/create', 'PageController@create')->name('page.create');
        Route::post('/page/create/store', 'PageController@store')->name('page.store');
        Route::get('/page/update/{page}', 'PageController@update')->name('page.update');
        Route::post('/page/update/put/{page}', 'PageController@put')->name('page.put');
        Route::get('/page/builder/{page}', 'PageController@builder')->name('page.builder');
        Route::post('/page/builder/save/{page}', 'PageController@save')->name('page.save');
        Route::post('/page/delete/{page}', 'PageController@delete')->name('page.delete');


        // Thema - pagina
        Route::get('/theme', 'ThemeController@index')->name('theme.index');
        Route::get('/theme/create', 'ThemeController@create')->name('theme.create');
        Route::post('/theme/create/store', 'ThemeController@store')->name('theme.store');
        Route::get('/theme/detail/{theme}', 'ThemeController@detail')->name('theme.detail');
        Route::get('/theme/update/{theme}', 'ThemeController@update')->name('theme.update');
        Route::post('/theme/update/put/{theme}', 'ThemeController@put')->name('theme.put');
        Route::post('/theme/delete/{theme}', 'ThemeController@delete')->name('theme.delete');


        // Variabele module
        Route::get('/ModuleItem/{module}', 'ModuleItemController@index')->name('moduleitem.index');
        Route::get('/ModuleItem/{module}/create', 'ModuleItemController@create')->name('moduleitem.create');
        Route::post('/ModuleItem/{module}/create/store', 'ModuleItemController@store')->name('moduleitem.store');
        Route::get('/ModuleItem/{module}/update/{item}', 'ModuleItemController@update')->name('moduleitem.update');
        Route::post('/ModuleItem/{module}/update/put/{item}', 'ModuleItemController@put')->name('moduleitem.put');
        Route::post('/ModuleItem/{module}/delete/{item}', 'ModuleItemController@delete')->name('moduleitem.delete');


        // Module - pagina
        Route::get('/module', 'ModuleController@index')->name('module.index');
        Route::get('/module/create', 'ModuleController@create')->name('module.create');
        Route::post('/modules/create/store', 'ModuleController@store')->name('module.store');
        Route::get('/modules/update/{module}', 'ModuleController@update')->name('module.update');
        Route::post('/modules/update/put/{module}', 'ModuleController@put')->name('module.put');
        Route::get('/modules/builder/{module}', 'ModuleController@builder')->name('module.builder');
        Route::post('/module/builder/save/{module}', 'ModuleController@save')->name('module.save');
        Route::post('/modules/delete/{module}', 'ModuleController@delete')->name('module.delete');


        // Templates - pagina
        Route::get('/template', 'TemplateController@index')->name('template.index');
        Route::get('/template/create', 'TemplateController@create')->name('template.create');
        Route::post('/template/create/store', 'TemplateController@store')->name('template.store');
        Route::get('/template/update/{template}', 'TemplateController@update')->name('template.update');
        Route::post('/template/update/put/{template}', 'TemplateController@put')->name('template.put');
        Route::get('/template/builder/{template}', 'TemplateController@builder')->name('template.builder');
        Route::post('/template/builder/save/{template}', 'TemplateController@save')->name('template.save');
        Route::post('/template/delete/{template}', 'TemplateController@delete')->name('template.delete');


        // Atribute - pagina
        Route::get('/attribute', 'AttributeController@index')->name('attribute.index');
        Route::get('/attribute/create', 'AttributeController@create')->name('attribute.create');
        Route::post('/attribute/create/store', 'AttributeController@store')->name('attribute.store');
        Route::get('/attribute/update/{attribute}', 'AttributeController@update')->name('attribute.update');
        Route::post('/attribute/update/put/{attribute}', 'AttributeController@put')->name('attribute.put');
        Route::post('/attribute/delete/{attribute}', 'AttributeController@delete')->name('attribute.delete');


        // Formulieren - pagina
        Route::get('/forms', 'FormsController@index')->name('forms.index');
        Route::get('/forms/create', 'FormsController@create')->name('forms.create');
        Route::post('/forms/create/store', 'FormsController@store')->name('forms.store');
        Route::get('/forms/update/{forms}', 'FormsController@update')->name('forms.update');
        Route::post('/forms/update/put/{forms}', 'FormsController@put')->name('forms.put');
        Route::post('/forms/delete/{forms}', 'FormsController@delete')->name('forms.delete');
        Route::get('/forms/builder/{forms}', 'FormsController@builder')->name('forms.builder');
        Route::post('/forms/builder/save/{forms}', 'FormsController@save')->name('forms.save');
        Route::get('/forms/export/{forms}', 'FormsController@export')->name('forms.export');


        // Mailen - pagina
        Route::get('/mails', 'MailController@index')->name('mails.index');
        Route::get('/mails/create', 'MailController@create')->name('mails.create');
        Route::post('/mails/create/store', 'MailController@store')->name('mails.store');
        Route::get('/mails/update/{mail}', 'MailController@update')->name('mails.update');
        Route::post('/mails/update/put/{mail}', 'MailController@put')->name('mails.put');
        Route::post('/mails/delete/{mail}', 'MailController@delete')->name('mails.delete');
        Route::get('/mails/builder/{mail}', 'MailController@builder')->name('mails.builder');
        Route::post('/mails/builder/save/{mail}', 'MailController@save')->name('mails.save');


        // Gebruikers - pagina
        Route::get('/user', 'UserController@index')->name('user.index');
        Route::get('/user/create', 'UserController@create')->name('user.create');
        Route::post('/user/create/store', 'UserController@store')->name('user.store');
        Route::get('/user/update/{id}', 'UserController@update')->name('user.update');
        Route::post('/user/update/put/{user}', 'UserController@put')->name('user.put');
        Route::post('/user/delete/{user}', 'UserController@delete')->name('user.delete');


        // Rechten - pagina
        Route::get('/role', 'RoleController@index')->name('role.index');
        Route::get('/role/create', 'RoleController@create')->name('role.create');
        Route::post('/role/create/store', 'RoleController@store')->name('role.store');
        Route::get('/role/update/{role}', 'RoleController@update')->name('role.update');
        Route::post('/role/update/put/{role}', 'RoleController@put')->name('role.put');
        Route::post('/role/delete/{role}', 'RoleController@delete')->name('role.delete');


        // Setting - pagina
        Route::get('/setting/{page}', 'SettingsController@index')->name('setting.index');
        Route::post('/setting/put/{page}', 'SettingsController@put')->name('setting.put');
});

// Alle prefixen van de voorkant 
Route::prefix('/')
    ->group(function () {
        Route::get('/', 'FrontendController@index');
        Route::get('/{page_name}', 'FrontendController@pages');
        Route::post('/{page_name}', 'FrontendController@pages');
        Route::get('/{page_name}/{detail}', 'FrontendController@detail');


        // Alle ajax requests
        Route::post('/ajax/post/createMailResult', function () {
            if (Request::ajax()) {
                $data = Request::except(['_token']);
                $form = App\FormsModel::where('name', $data['name'])->get()->first();
                DB::table('forms_'.$data['name'])->insert(Request::except(['name', '_token']));
                Mail::to($data['Email'], $data['Voornaam'])->send(new App\Mail\ResponseForm($data, $form->Mails->MailData));

                return response()->json(['msg' => 'Het werkt']);
            } else {
                return response()->json(['msg' => 'Het werkt niet'], 406);
            }   
        });

        Route::post('/ajax/post/updateMessage', function () {
            if (Request::ajax()) {
                $data = Request::except(['_token']);
                $message = App\MessageModel::find($data['id']);
                $message->update($data);
                return response()->json(['msg', 'Het werkt'], 200);
            }

            return response()->json(['msg' => 'Het werkt niet'], 406);
        });
});

app/Http/Controllers/AttributeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\AttributeModel;
use Illuminate\Support\Facades\Response;
use Carbon\Carbon;
use App\MessageModel;

class AttributeController extends Controller
{
    /**
     * @var Carbon $date
     */
    protected $_date;


    /**
     * Constructor 
     */
    public function __construct()
    {
        $this->_date = Carbon::now();
    }


    /**
     * Functie voor het ophalen van de readpagina
     * 
     * @return Illuminate\Http\Request view;
     */
    public function index()
    {
        $this->middleware('checkrole:24');

        $attributes = AttributeModel::get();

        return view('attributes.read', compact('attributes'));
    }


    /**
     * Functie voor het aanmaken van de attribute gegevens
     * 
     * @return Illuminate\Http\Request view;
     */
    public function create()
    {
        $this->middleware('checkrole:25');

        return view('attributes.create');
    }


    /**
     * Funcite voor het opslaan vande gegevens
     * 
     * @param Request $request
     * @return Illuminate\Http\Request redirect;
     */
    public function store(Request $request)
    {
        AttributeModel::create($this->transformForm($request));
        $this->createMessage(['Succes','Attribute succesvol aangemaakt','fas fa-check-circle',0,$this->_date->toDateString(),$this->_date->toTimeString(),]);
        return redirect('/admin/attribute')->with('status', 'Attribute succesvol aangemaakt');
    }


    /**
     * Functie voor het laden van de update gegevens
     * 
     * @param Object $id
     * @return Illuminate\Http\Request view;
     */
    public function update(AttributeModel $attribute)
    {
        $this->middleware('checkrole:26');

        return view('attributes.update', compact('attribute'));
    }


    /**
     * Functie voor het opslaan van de geupdatete gegevens
     * 
     * @param Request $request;
     * @param AttributeModel $attribute;
     * @return Illuminate\Http\Request redirect;
     */
    public function put(Request $request, AttributeModel $attribute)
    {
        $attribute->update($this->transformForm($request));
        $this->createMessage(['Succes','Attribute succesvol geüpdated','fas fa-check-circle',0,$this->_date->toDateString(),$this->_date->toTimeString(),]);
        return redirect('/admin/attribute')->with('status', 'Attribute succesvol geüpdated');
    }


    /**
     * Functie voor het verwijderen van de gegevens
     * 
     * @param AttributeModel $attribute;
     * @return Illuminate\Http\Request redirect;
     */
    public function delete(AttributeModel $attribute)
    {
        $this->middleware('checkrole:27');

        $attribute->delete();
        $this->createMessage(['Succes','Attribute succesvol verwijderd','fas fa-check-circle',0,$this->_date->toDateString(),$this->_date->toTimeString(),]);
        return redirect('/admin/attribute')->with('status', 'Attribute succesvol verwijderd');
    }

    
    /**
     * Functie voor het maken van values
     * 
     * @param Request $request;
     * @return String 
     */
    private function getValue(Request $request) : string
    {
        if (isset($request->value)) {
            $array = [];
            foreach ($request->value as $item) {
                array_push($array, $item);
            }

            return implode(';', $array);
        } else {
            return "";
        }
    }


    /**
     * Functie voor het aanmaken van een melding
     * 
     * @param array $data
     * @return MessageModel 
     */
    private function createMessage(array $data)
    {
        return MessageModel::create([
            'name' => $data[0],
            'message' => $data[1],
            'image' => $data[2],
            'read' => $data[3],
            'date' => $data[4],
            'time' => $data[5],
        ]);
    }


    /**
     * Return van de standaard array
     * 
     * @param Object $request;
     * @param Object $attribute;
     * @return array
     */
    private function transformForm($request) : array
    {
        return [
            'name' => $request->input('name'),
            'group' => $request->input('group'),
            'type' => $request->input('type'),
            'value' => $this->getValue($request),
            'required' => $request->input('required'),
            'used' => 0,
        ];
    }
}

resources/views/attributes/create.blade.php
@extends('layouts.master')
@section('title', 'Attributes | create')
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Attributes
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.attribute.index') }}">Attributen</a></li>
      <li><a href="{{ route('admin.attribute.create') }}">Attributen aanmaken</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Attributes</h3>
        </div>

        <form action="{{ route('admin.attribute.store') }}" method="POST">
            <div class="row">
                <div class="col-md-6" >
                    <div class="form-group">
                        <label class="form-text">Naam:</label>
                        <input type="text" name="name" class="form-control" placeholder="Naam.." />
                    </div>

                    <div class="form-group">
                          <label class="form-text">Groep:</label>
                          <select name="group" class="form-control">
                            <option value="main">Main</option>
                                <option value="header">Header</option>
                                <option value="body">Body</option>
                                <option value="footer">Footer</option>
                            </select>
                    </div>

                    <div id="attribute-value" class="attribute-value" style="display: none;">
                      <div id="value-input" class="form-group">
                              <label class="form-text">Field 1</label>
                              <input type="text" name="value[1]" class="form-control" placeholder="Field.." />
                              <br />
                      </div>

                      <button onclick="addFields();return false;" class="btn btn-primary"><i class="fas fa-plus-square"></i></button>
                      <button onclick="removeFields();return false;" class="btn btn-primary"><i class="fas fa-minus-square"></i></button>
                  </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label class="form-text">Verplicht:</label>
                        <select name="required" class="form-control">
                            <option value=1>Ja</option>
                            <option value=0 selected>Nee</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="form-text">Type:</label>
                        <select id="select-attribute" name="type" class="form-control">
                            <option value="text">Text</option>
                            <option value="number">Getal</option>
                            <option value="valuta">Valuta</option>
                            <option value="image">Afbeelding</option>
                            <option value="radio">Radio</option>
                            <option value="select">Select</option>
                            <option value="textarea">Textbox</option>
                            <option value="password">Wachtwoord</option>
                            <option value="email">Email</option>
                            <option value="time">Tijd</option>
                            <option value="date">Date</option>
                        </select>
                    </div>

                    <div class="form-group">
                        @csrf
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Attribute opslaan" />
                    </div>
                </div>
            </div>
        </form>
    </div>
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
  var attribute_form = document.getElementById('attribute-value');
  var attribute_select = document.getElementById('select-attribute');
  var counter = 1;

  if (attribute_select.value == 'select') {
      attribute_form.style.display = "block";
  } else if (attribute_form.value == 'radio') {
      attribute_form.style.display = 'block';
  } else {
      attribute_form.style.display = 'none';
  }

  attribute_select.onchange = function() {
    if (attribute_select.value == 'select') {
      attribute_form.style.display = "block";
    } else if (attribute_select.value == 'radio') {
      attribute_form.style.display = "block";
    } else {
      attribute_form.style.display = "none";
    }
  }

  function addFields() {
      counter += 1;

      let label = document.createElement('label');
      let field = document.createElement('input');
      let br = document.createElement('br');

      label.className = 'form-text';
      label.textContent = `Field ${counter}`;
      label.id = `label${counter}`;

      field.type = 'text';
      field.name = 'value['+counter+']';
      field.id = `select${counter}`;
      field.className = 'form-control';
      field.placeholder = 'Field..';

      br.id = `id${counter}`;

      document.getElementById('value-input').appendChild(label);
      document.getElementById('value-input').appendChild(field);
      document.getElementById('value-input').appendChild(br);
  }


  function removeFields() {
    if (document.getElementById(`label${counter}`) && document.getElementById(`select${counter}`)) {
      let label = document.getElementById(`label${counter}`);
      let field = document.getElementById(`select${counter}`);
      let br = document.getElementbyId(`id${counter}`);

      counter -= 1;

      document.getElementById('value-input').removeChild(field);
      document.getElementById('value-input').removeChild(label);
      document.getElementById('value-input').removeChild(br);
    }
    
    return false;
  }
</script>
@endsection

resources/views/attributes/read.blade.php
@extends('layouts.master')
@section('title', 'Attributes | read')
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Attributes
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.attribute.index') }}">Attributen</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Attributes</h3>
            <a class="btn btn-success pull-right" href="{{ route('admin.attribute.create') }}">Nieuw</a>
        </div>

        <table id="myexample" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Naam</th>
                    <th>Groep</th>
                    <th>Type</th>
                    <th>Bewerken</th>
                    <th>Verwijderen</th>
                </tr>
            </thead>
            <tbody>
                @foreach($attributes as $attribute)
                    <tr class="table_row">
                        <td>{{ $attribute->id }}</td>
                        <td>{{ $attribute->name }}</td>
                        <td>{{ $attribute->group }}</td>
                        <td>{{ $attribute->type }}</td>
                        <td><a class="btn btn-warning" href="{{ route('admin.attribute.update', [$attribute->id]) }}"><i class="fas fa-pencil-alt"></i></a></td>
                        <td><a class="btn btn-danger" href="{{ route('admin.attribute.delete', [$attribute->id]) }}"
                          onclick="event.preventDefault();sure();document.getElementById('delete-form').submit();">
                          <i class="far fa-trash-alt"></i></a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>

    <form id="delete-form" method="post" action="{{ route('admin.attribute.delete', [$attribute->id ?? '']) }}" style="display:none;">
        @csrf
      </form>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
$(function () {
        $('#myexample').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });

    function sure() {
      return confirm("Weet je het zeker dat je de Attribute wilt verwijderen!");
    }
  </script>

@endsection

resources/views/attributes/update.blade.php
@extends('layouts.master')
@section('title', 'Attributes | update')
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Attributes
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.attribute.index') }}">Attributen</a></li>
      <li><a href="{{ route('admin.attribute.update', [$attribute->id]) }}">Attributen updaten</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Attributes</h3>
        </div>

        <form action="{{ route('admin.attribute.put', [$attribute->id]) }}" method="POST">
            <div class="row">
                <div class="col-md-6" >
                    <div class="form-group">
                        <label class="form-text">Naam:</label>
                        <input type="text" name="name" value="{{ $attribute->name }}" class="form-control" placeholder="Naam.." />
                    </div>

                    <div class="form-group">
                          <label class="form-text">Groep:</label>
                          <select name="group" class="form-control">
                                <option value="main" @if($attribute->group == 'main') selected @endif>Main</option>
                                <option value="header" @if($attribute->group == 'header') selected @endif>Header</option>
                                <option value="body" @if($attribute->group == 'body') selected @endif>Body</option>
                                <option value="footer" @if($attribute->group == 'footer') selected @endif>Footer</option>
                            </select>
                    </div>

                    <div id="attribute-value" class="attribute-value" style="display: none;">
                        <div id="value-input" class="form-group">
                            @if (!empty($attribute->value))
                                @foreach (explode(';', $attribute->value) as $key => $val)
                                    <label class="form-text">Select {{ $key }}</label>
                                    <input type="text" name="value[{{ $key }}]" value="{{ $val }}" class="form-control" placeholder="Select.." />
                                    <br />
                                @endforeach
                            @else
                                <label class="form-text">Field 1</label>
                                <input type="text" name="value[1]" class="form-control" placeholder="Field.." />
                                <br />
                            @endif
                        </div>

                        <button onclick="addFields();return false;" class="btn btn-primary"><i class="fas fa-plus-square"></i></button>
                        <button onclick="removeFields();return false;" class="btn btn-primary"><i class="fas fa-minus-square"></i></button>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label class="form-text">Verplicht:</label>
                        <select name="required" class="form-control">
                            <option value=1 @if($attribute->required == 1) selected @endif>Ja</option>
                            <option value=0 @if($attribute->required == 0) selected @endif>Nee</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="form-text">Type:</label>
                        <select id="select-attribute" name="type" class="form-control">
                            <option value="text" @if($attribute-> type == 'text') selected @endif>Text</option>
                            <option value="number" @if($attribute-> type == 'number') selected @endif>Getal</option>
                            <option value="valuta" @if($attribute-> type == 'valuta') selected @endif>Valuta</option>
                            <option value="image" @if($attribute-> type == 'image') selected @endif>Afbeelding</option>
                            <option value="radio" @if($attribute-> type == 'radio') selected @endif>Radio</option>
                            <option value="select" @if($attribute-> type == 'select') selected @endif>Select</option>
                            <option value="textarea" @if($attribute-> type == 'textarea') selected @endif>Textbox</option>
                            <option value="password" @if($attribute-> type == 'password') selected @endif>Wachtwoord</option>
                            <option value="email" @if($attribute-> type == 'email') selected @endif>Email</option>
                            <option value="time" @if($attribute-> type == 'time') selected @endif>Tijd</option>
                            <option value="date" @if($attribute-> type == 'date') selected @endif>Date</option>
                        </select>
                    </div>

                    <div class="form-group">
                        @csrf
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Attribute opslaan" />
                    </div>
                </div>
            </div>
        </form>
        
    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
    var attribute_form = document.getElementById('attribute-value');
    var attribute_select = document.getElementById('select-attribute');
    var counter = 1;
  
    if (attribute_select.value == 'select') {
        attribute_form.style.display = "block";
    } else if (attribute_form.value == 'radio') {
        attribute_form.style.display = 'block';
    } else {
        attribute_form.style.display = 'none';
    }
  
    attribute_select.onchange = function() {
      if (attribute_select.value == 'select') {
        attribute_form.style.display = "block";
      } else if (attribute_select.value == 'radio') {
        attribute_form.style.display = "block";
      } else {
        attribute_form.style.display = "none";
      }
    }
  
    function addFields() {
        counter += 1;
  
        let label = document.createElement('label');
        let field = document.createElement('input');
        let br = document.createElement('br');
  
        label.className = 'form-text';
        label.textContent = `Field ${counter}`;
        label.id = `label${counter}`;
  
        field.type = 'text';
        field.name = 'value['+counter+']';
        field.id = `select${counter}`;
        field.className = 'form-control';
        field.placeholder = 'Field..';
  
        br.id = `id${counter}`;
  
        document.getElementById('value-input').appendChild(label);
        document.getElementById('value-input').appendChild(field);
        document.getElementById('value-input').appendChild(br);
    }
  
  
    function removeFields() {
      if (document.getElementById(`label${counter}`) && document.getElementById(`select${counter}`)) {
        let label = document.getElementById(`label${counter}`);
        let field = document.getElementById(`select${counter}`);
        let br = document.getElementbyId(`id${counter}`);
  
        counter -= 1;
  
        document.getElementById('value-input').removeChild(field);
        document.getElementById('value-input').removeChild(label);
        document.getElementById('value-input').removeChild(br);
      }
      
      return false;
    }
  </script>
@endsection