routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();  

// Alle prefixen van het CMS
Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function() {

        // Dashboard controller
        Route::get('/', 'DashboardController@index')->name('index');


        // Menu - pagina
        Route::get('/menu', 'MenuController@index')->name('menu.index');
        Route::post('/menu/store', 'MenuController@store')->name('menu.store');
        Route::post('/menu/put/{$menu}', 'MenuController@put')->name('menu.put');
        Route::post('/menu/delete/{$menu}', 'MenuController@delete')->name('menu.delete');
        

        // Pagina - pagina
        Route::get('/page', 'PageController@index')->name('page.index');
        Route::get('/page/create', 'PageController@create')->name('page.create');
        Route::post('/page/create/store', 'PageController@store')->name('page.store');
        Route::get('/page/update/{page}', 'PageController@update')->name('page.update');
        Route::post('/page/update/put/{page}', 'PageController@put')->name('page.put');
        Route::get('/page/builder/{page}', 'PageController@builder')->name('page.builder');
        Route::post('/page/builder/save/{page}', 'PageController@save')->name('page.save');
        Route::post('/page/delete/{page}', 'PageController@delete')->name('page.delete');


        // Thema - pagina
        Route::get('/theme', 'ThemeController@index')->name('theme.index');
        Route::get('/theme/create', 'ThemeController@create')->name('theme.create');
        Route::post('/theme/create/store', 'ThemeController@store')->name('theme.store');
        Route::get('/theme/detail/{theme}', 'ThemeController@detail')->name('theme.detail');
        Route::get('/theme/update/{theme}', 'ThemeController@update')->name('theme.update');
        Route::post('/theme/update/put/{theme}', 'ThemeController@put')->name('theme.put');
        Route::post('/theme/delete/{theme}', 'ThemeController@delete')->name('theme.delete');


        // Variabele module
        Route::get('/ModuleItem/{module}', 'ModuleItemController@index')->name('moduleitem.index');
        Route::get('/ModuleItem/{module}/create', 'ModuleItemController@create')->name('moduleitem.create');
        Route::post('/ModuleItem/{module}/create/store', 'ModuleItemController@store')->name('moduleitem.store');
        Route::get('/ModuleItem/{module}/update/{item}', 'ModuleItemController@update')->name('moduleitem.update');
        Route::post('/ModuleItem/{module}/update/put/{item}', 'ModuleItemController@put')->name('moduleitem.put');
        Route::post('/ModuleItem/{module}/delete/{item}', 'ModuleItemController@delete')->name('moduleitem.delete');


        // Module - pagina
        Route::get('/module', 'ModuleController@index')->name('module.index');
        Route::get('/module/create', 'ModuleController@create')->name('module.create');
        Route::post('/modules/create/store', 'ModuleController@store')->name('module.store');
        Route::get('/modules/update/{module}', 'ModuleController@update')->name('module.update');
        Route::post('/modules/update/put/{module}', 'ModuleController@put')->name('module.put');
        Route::get('/modules/builder/{module}', 'ModuleController@builder')->name('module.builder');
        Route::post('/module/builder/save/{module}', 'ModuleController@save')->name('module.save');
        Route::post('/modules/delete/{module}', 'ModuleController@delete')->name('module.delete');


        // Templates - pagina
        Route::get('/template', 'TemplateController@index')->name('template.index');
        Route::get('/template/create', 'TemplateController@create')->name('template.create');
        Route::post('/template/create/store', 'TemplateController@store')->name('template.store');
        Route::get('/template/update/{template}', 'TemplateController@update')->name('template.update');
        Route::post('/template/update/put/{template}', 'TemplateController@put')->name('template.put');
        Route::get('/template/builder/{template}', 'TemplateController@builder')->name('template.builder');
        Route::post('/template/builder/save/{template}', 'TemplateController@save')->name('template.save');
        Route::post('/template/delete/{template}', 'TemplateController@delete')->name('template.delete');


        // Atribute - pagina
        Route::get('/attribute', 'AttributeController@index')->name('attribute.index');
        Route::get('/attribute/create', 'AttributeController@create')->name('attribute.create');
        Route::post('/attribute/create/store', 'AttributeController@store')->name('attribute.store');
        Route::get('/attribute/update/{attribute}', 'AttributeController@update')->name('attribute.update');
        Route::post('/attribute/update/put/{attribute}', 'AttributeController@put')->name('attribute.put');
        Route::post('/attribute/delete/{attribute}', 'AttributeController@delete')->name('attribute.delete');


        // Formulieren - pagina
        Route::get('/forms', 'FormsController@index')->name('forms.index');
        Route::get('/forms/create', 'FormsController@create')->name('forms.create');
        Route::post('/forms/create/store', 'FormsController@store')->name('forms.store');
        Route::get('/forms/update/{forms}', 'FormsController@update')->name('forms.update');
        Route::post('/forms/update/put/{forms}', 'FormsController@put')->name('forms.put');
        Route::post('/forms/delete/{forms}', 'FormsController@delete')->name('forms.delete');
        Route::get('/forms/builder/{forms}', 'FormsController@builder')->name('forms.builder');
        Route::post('/forms/builder/save/{forms}', 'FormsController@save')->name('forms.save');
        Route::get('/forms/export/{forms}', 'FormsController@export')->name('forms.export');


        // Mailen - pagina
        Route::get('/mails', 'MailController@index')->name('mails.index');
        Route::get('/mails/create', 'MailController@create')->name('mails.create');
        Route::post('/mails/create/store', 'MailController@store')->name('mails.store');
        Route::get('/mails/update/{mail}', 'MailController@update')->name('mails.update');
        Route::post('/mails/update/put/{mail}', 'MailController@put')->name('mails.put');
        Route::post('/mails/delete/{mail}', 'MailController@delete')->name('mails.delete');
        Route::get('/mails/builder/{mail}', 'MailController@builder')->name('mails.builder');
        Route::post('/mails/builder/save/{mail}', 'MailController@save')->name('mails.save');


        // Gebruikers - pagina
        Route::get('/user', 'UserController@index')->name('user.index');
        Route::get('/user/create', 'UserController@create')->name('user.create');
        Route::post('/user/create/store', 'UserController@store')->name('user.store');
        Route::get('/user/update/{id}', 'UserController@update')->name('user.update');
        Route::post('/user/update/put/{user}', 'UserController@put')->name('user.put');
        Route::post('/user/delete/{user}', 'UserController@delete')->name('user.delete');


        // Rechten - pagina
        Route::get('/role', 'RoleController@index')->name('role.index');
        Route::get('/role/create', 'RoleController@create')->name('role.create');
        Route::post('/role/create/store', 'RoleController@store')->name('role.store');
        Route::get('/role/update/{role}', 'RoleController@update')->name('role.update');
        Route::post('/role/update/put/{role}', 'RoleController@put')->name('role.put');
        Route::post('/role/delete/{role}', 'RoleController@delete')->name('role.delete');


        // Setting - pagina
        Route::get('/setting/{page}', 'SettingsController@index')->name('setting.index');
        Route::post('/setting/put/{page}', 'SettingsController@put')->name('setting.put');
});

// Alle prefixen van de voorkant 
Route::prefix('/')
    ->group(function () {
        Route::get('/', 'FrontendController@index');
        Route::get('/{page_name}', 'FrontendController@pages');
        Route::post('/{page_name}', 'FrontendController@pages');
        Route::get('/{page_name}/{detail}', 'FrontendController@detail');


        // Alle ajax requests
        Route::post('/ajax/post/createMailResult', function () {
            if (Request::ajax()) {
                $data = Request::except(['_token']);
                $form = App\FormsModel::where('name', $data['name'])->get()->first();
                DB::table('forms_'.$data['name'])->insert(Request::except(['name', '_token']));
                Mail::to($data['Email'], $data['Voornaam'])->send(new App\Mail\ResponseForm($data, $form->Mails->MailData));

                return response()->json(['msg' => 'Het werkt']);
            } else {
                return response()->json(['msg' => 'Het werkt niet'], 406);
            }   
        });

        Route::post('/ajax/post/updateMessage', function () {
            if (Request::ajax()) {
                $data = Request::except(['_token']);
                $message = App\MessageModel::find($data['id']);
                $message->update($data);
                return response()->json(['msg', 'Het werkt'], 200);
            }

            return response()->json(['msg' => 'Het werkt niet'], 406);
        });
});

resources/views/pages/builder.blade.php
@extends('layouts.master')
@section('title', 'Pages | builder')
{{-- @include('partials.meta'); --}}
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pages 
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="{{ route('admin.page.index') }}"></i>Pagina's</a></li>
        <li><a href="{{ route('admin.page.builder', [$page->id]) }}"></i>Pagina builder</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <form action="{{ route('admin.page.save', [$page->id]) }}" method="POST" enctype="multipart/form-data">
        <!-- main tag -->
        <div class="box box-primary" style="border-top-color: #1AA650;">
            <div class="box-header with-border">
                <h3 class="box-title">Main</h3>
            </div>
                
            <div class="row">
                @if (count($attributes_main) > 0)
                    @foreach($attributes_main as $value)
                        @include('partials.fields.'.$value->Attributes->type.'_field')
                    @endforeach
                @else 
                    <h3 style="text-align: center;">Helaas, geen attributen gevonden</h3>
                @endif
            </div>

        </div>

        <!-- header tag -->
        <div class="box box-primary" style="border-top-color: #1AA650;">
            <div class="box-header with-border">
                <h3 class="box-title">Header</h3>
            </div>
                
            <div class="row">
                @if (count($attributes_header) > 0)
                    @foreach($attributes_header as $value)
                        @include('partials.fields.'.$value->Attributes->type.'_field')
                    @endforeach
                @else 
                    <h3 style="text-align: center;">Geen attributen gevonden</h3>
                @endif
            </div>

        </div>
    
        <!-- body tag -->
        <div class="box box-primary" style="border-top-color: #1AA650;">
            <div class="box-header with-border">
                <h3 class="box-title">Body</h3>
            </div>
                
            <div class="row">
                @if (count($attributes_body) > 0)
                    @foreach($attributes_body as $value)
                        @include('partials.fields.'.$value->Attributes->type.'_field')
                    @endforeach
                @else 
                    <h3 style="text-align: center;">Geen attributen gevonden</h3>
                @endif
            </div>

        </div>

        <!-- footer tag -->
        <div class="box box-primary" style="border-top-color: #1AA650;">
            <div class="box-header with-border">
                <h3 class="box-title">Footer</h3>
            </div>
                
            <div class="row">
                @if (count($attributes_footer) > 0)
                    @foreach($attributes_footer as $value)
                        @include('partials.fields.'.$value->Attributes->type.'_field')
                    @endforeach    
                @else 
                    <h3 style="text-align: center;">Geen attributen gevonden</h3>
                @endif
            </div>

        </div>

        <!-- slug tag -->
        <div class="box box-primary" style="border-top-color: #1AA650;">
            <div class="box-header with-border">
                <h3 class="box-title">Slug</h3>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <!-- Slug titel -->
                    <div class="form-group">
                        <label class="form-text">Slug titel *  (max 255 characters)</label>
                        <input type="text" name="page[slug_titel]" class="form-control" value="{{ $page_data->slug_titel ?? '' }}" required placeholder="Slug titel.." />
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <!-- Slug verhaal -->
                    <div class="form-group">
                        <label class="form-text">Slug verhaal (max 255 characters)</label>
                        <textarea class="form-control" name="page[slug_story]" value="{{ $page_data->slug_story ?? '' }}"></textarea>
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <!-- slug url -->
                    <div class="form-group">
                        <label class="form-text">Slug url *  (max 255 characters)</label>
                        <input type="text" name="page[slug_url]" class="form-control" value="{{ $page_data->slug_url ?? '' }}" required placeholder="Slug url.." /> 
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
                
            <div class="form-group">
                @csrf
                <input type="submit" name="submit" class="btn btn-succes" value="Pagina opslaan" />
            </div>
            
        </div>
    </form>

    

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
    let input = document.getElementsByClassName('text_form');
    for (let x of input) {
        x.click(function() {
            console.log(x);
        });
    }

    $('.button_id').bind('click', getFile);
    function getFile() {
      $(this).prev().click();
  }

  function readImgURL(input) {
          if (input.files && input.files[0]) {
              var reader = new FileReader();
  
              reader.onload = function(e) {
                $(input).next().children('.imgPrev').attr('src', e.target.result);
              }
  
              $(input).next().children('.imgText').hide();
              $(input).next().children('.imgPrev').show();
  
              reader.readAsDataURL(input.files[0]);
          }
      }

      $(".button_id").prev().change(function () {
          readImgURL(this);
      });

      if ($('.imgPrev').val() !== null) {
        $(this).show();
        $(this).next().hide();
      }

</script>
@endsection

resources/views/pages/create.blade.php
@extends('layouts.master')
@section('title', 'Pages | create')
{{-- @include('partials.meta'); --}}
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pages
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.page.index') }}"></i>Pagina's</a></li>
      <li><a href="{{ route('admin.page.create') }}"></i>Pagina's aanmaken</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Pages</h3>
        </div>
        
        <form action="{{ route('admin.page.store') }}" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <!-- Naam -->
                    <div class="form-group">
                        <label class="form-text">Naam: *</label>
                        <input type="text" name="name" class="form-control" placeholder="Naam.." />
                    </div>
                    <!-- Slug -->
                    <div class="form-group">
                        <label class="form-text">Slug: *</label>
                        <input type="text" name="view" class="form-control" placeholder="Slug.." />
                    </div>
                </div>

                <div class="col-md-6">
                    <!-- Icoon -->
                    <div class="form-group">
                        <label class="form-text">Icoon: (Volledige fontawesome tag)</label>
                        <input type="text" name="icon" class="form-control" placeholder="Icoon.." />
                    </div>
                    <!-- Template -->
                    <div class="form-group">
                      <label class="form-text">Template</label>
                      <select name="template" class="form-control">
                        @foreach($templates as $template)
                          <option value="{{ $template->id }}">{{ $template->name }}</option>
                        @endforeach
                      </select>
                  </div>
                    <!-- Submitknop -->
                    <div class="form-group">
                        @csrf
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Pagina opslaan" />
                    </div>
                </div>
            </div>
        </form>
        
    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection

resources/views/pages/read.blade.php
@extends('layouts.master')
@section('title', 'Pages | read')
{{-- @include('partials.meta'); --}}
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pages
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.page.index') }}"></i>Pagina's</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Pages</h3>
            <a class="btn btn-success pull-right" href="{{ route('admin.page.create') }}">Nieuw</a>
        </div>

        <table id="myexample" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Naam</th>
                    <th>Icoon</th>
                    <th>Slug</th>
                    <th>Gecreeërd op</th>
                    <th>Builder</th>
                    <th>Updaten</th>
                    <th>Verwijderen</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($pages as $page)
                    <tr class="table_row">
                        <td>{{ $page->id }}</td>
                        <td>{{ $page->name }}</td>
                        <td>{{ $page->icon }}</td>
                        <td>{{ $page->view }}</td>
                        <td>{{ $page->created_at }}
                        <td><a class="btn btn-info" href="{{ route('admin.page.builder', $page->id) }}"><i class="fas fa-cog"></i></a></td>
                        <td><a class="btn btn-warning" href="{{ route('admin.page.update', $page->id) }}"><i class="fas fa-pencil-alt"></i></a></td>
                        <td><a class="btn btn-danger" href="{{ route('admin.page.delete', $page->id) }}"
                          onclick="event.preventDefault();sure();document.getElementById('delete-form').submit();">
                          <i class="far fa-trash-alt"></i></a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>

    <form id="delete-form" method="post" action="{{ route('admin.page.delete', [$page->id ?? '']) }}" style="display:none;">
        @csrf
      </form>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->


<script>
    $(function () {
        $('#myexample').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
    


function sure() {
  return confirm("Weet je het zeker dat je de gebruiker wilt verwijderen!");
}
</script>

@endsection

resources/views/pages/update.blade.php
@extends('layouts.master')
@section('title', 'Pages | update')
{{-- @include('partials.meta'); --}}
@section('content')
  @parent
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pages
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i>Home</a></li>
      <li><a href="{{ route('admin.page.index') }}"></i>Pagina's</a></li>
      <li><a href="{{ route('admin.page.update', [$page->id]) }}"></i>Pagina's updaten</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="box box-primary" style="border-top-color: #1AA650;">
        <div class="box-header with-border">
            <h3 class="box-title">Pages</h3>
        </div>
        
        <form action="{{ route('admin.page.put', [$page->id]) }}" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <!-- Naam -->
                    <div class="form-group">
                        <label class="form-text">Naam: *</label>
                        <input type="text" name="name" class="form-control" value="{{ $page->name }}" placeholder="Naam.." />
                    </div>
                    <!-- Slug -->
                    <div class="form-group">
                        <label class="form-text">Slug: *</label>
                        <input type="text" name="view" class="form-control" value="{{ $page->view }}" placeholder="Slug.." />
                    </div>
                </div>

                <div class="col-md-6">
                    <!-- Icoon -->
                    <div class="form-group">
                        <label class="form-text">Icoon: (Volledige fontawesome tag)</label>
                        <input type="text" name="icon" class="form-control" value="{{ $page->icon }}" placeholder="Icoon.." />
                    </div>
                    <!-- Template -->
                    <div class="form-group">
                      <label class="form-text">Template</label>
                      <select name="template" class="form-control">
                        @foreach($templates as $template)
                          <option value="{{ $template->id }}" @if($page->template_id == $template->id) selected @endif>{{ $template->name }}</option>
                        @endforeach
                      </select>
                  </div>
                    <!-- Submitknop -->
                    <div class="form-group">
                        @csrf
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Pagina updaten" />
                    </div>
                </div>
            </div>
        </form>
        
    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection